name: Update Calendar

on:
  schedule:
    - cron: '30 * * * *' # This schedule is set to run every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # This step checks out a copy of your repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install pipenv
      run: |
        python -m pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install

    - name: Run script
      run: pipenv run python generate_calendar.py
      env: 
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}

    - name: Commit and push changes
      run: |
        git config --global user.name 'Automated Push' # Replace with your name
        git config --global user.email 'Automatic@user.com' # Replace with your email
        git checkout gh-pages
        git add twitch-calendar.ics # Replace with the path to your file
        git commit -m 'Update Calendar'
        git push